import * as p from '@clack/prompts'
import { writeFileSync, existsSync, readFileSync } from 'fs'
import { dynadot, assertDynadotOk, ENV_GROUPS, requireEnv } from '../_lib.ts'

requireEnv(ENV_GROUPS.dynadot)

p.intro('🌐 Skill 1 — Domain Setup')

const brandName = await p.text({
  message: 'What is your brand / company name?',
  placeholder: 'e.g. Nait Allen Growth',
  validate: v => (!v ? 'Required' : undefined),
})
if (p.isCancel(brandName)) {
  p.cancel('Cancelled')
  process.exit(0)
}

const domainCount = await p.text({
  message: 'How many domains do you want to buy?',
  placeholder: 'e.g. 5',
  validate: v => (isNaN(Number(v)) || Number(v) < 1 ? 'Enter a valid number' : undefined),
})
if (p.isCancel(domainCount)) {
  p.cancel('Cancelled')
  process.exit(0)
}

const maxDomains = Number(domainCount)

const extensions = await p.multiselect({
  message: 'Which extensions to check?',
  options: [
    { value: '.com', label: '.com', hint: 'recommended' },
    { value: '.io', label: '.io' },
    { value: '.co', label: '.co' },
    { value: '.net', label: '.net' },
    { value: '.ai', label: '.ai' },
  ],
  initialValues: ['.com'],
})
if (p.isCancel(extensions)) {
  p.cancel('Cancelled')
  process.exit(0)
}

const base = (brandName as string).toLowerCase().replace(/[^a-z0-9]/g, '')
const prefixes = ['get', 'use', 'try', 'go', 'with']
const suffixes = ['hq', 'agency', 'growth', 'labs', 'co']

const candidates: string[] = []
for (const ext of extensions as string[]) {
  candidates.push(`${base}${ext}`)
}
for (const pre of prefixes) {
  for (const ext of extensions as string[]) {
    candidates.push(`${pre}${base}${ext}`)
  }
}
for (const suf of suffixes) {
  for (const ext of extensions as string[]) {
    candidates.push(`${base}${suf}${ext}`)
  }
}

const confirmList = await p.confirm({
  message: `I'll check availability for ${candidates.length} domain variations of "${brandName}". Proceed?`,
})
if (p.isCancel(confirmList) || !confirmList) {
  p.cancel('Cancelled')
  process.exit(0)
}

const spinner = p.spinner()
spinner.start('Checking availability...')

const available: string[] = []

try {
  const chunks: string[][] = []
  for (let i = 0; i < candidates.length; i += 10) {
    chunks.push(candidates.slice(i, i + 10))
  }

  for (const chunk of chunks) {
    const params: Record<string, string> = { command: 'search' }
    chunk.forEach((domain, i) => {
      params[`domain${i}`] = domain
    })

    const data = await dynadot.get(params)
    assertDynadotOk(data, 'SearchResponse')

    const results = (data.SearchResponse as { SearchResults?: { DomainName: string; Available: string }[] })
      ?.SearchResults
    if (results) {
      for (const result of results) {
        if (result.Available === 'yes') available.push(result.DomainName)
      }
    }
  }

  spinner.stop(`Found ${available.length} available domains`)
} catch (err) {
  spinner.stop('Failed to check availability')
  p.log.error(`❌ ${err}`)
  process.exit(1)
}

if (available.length === 0) {
  p.log.warn('No domains available. Try a different brand name.')
  process.exit(0)
}

const selected = await p.multiselect({
  message: `Select up to ${maxDomains} domain(s) to register:`,
  options: available.map(d => ({ value: d, label: d })),
})
if (p.isCancel(selected)) {
  p.cancel('Cancelled')
  process.exit(0)
}

let domains = selected as string[]

if (domains.length > maxDomains) {
  p.log.warn(`Selected ${domains.length}; keeping first ${maxDomains} (your requested count).`)
  domains = domains.slice(0, maxDomains)
}

if (domains.length === 0) {
  p.log.warn('No domains selected.')
  process.exit(0)
}

const confirmPurchase = await p.confirm({
  message:
    `Registering ${domains.length} domain(s):\n${domains.map(d => `  • ${d}`).join('\n')}\n` +
    `This will charge your Dynadot account. Proceed?`,
})
if (p.isCancel(confirmPurchase) || !confirmPurchase) {
  p.cancel('Cancelled')
  process.exit(0)
}

const registered: string[] = []
const failed: string[] = []

const regSpinner = p.spinner()
regSpinner.start('Registering domains...')

for (const domain of domains) {
  try {
    const data = await dynadot.get({
      command: 'register',
      domain,
      duration: '1',
    })
    assertDynadotOk(data, 'RegisterResponse')
    registered.push(domain)
    p.log.success(`✓ ${domain}`)
  } catch (err) {
    failed.push(domain)
    p.log.error(`❌ ${domain} — ${err}`)
  }
}

regSpinner.stop('Registration complete')

if (registered.length > 0) {
  const existing = existsSync('domains.txt')
    ? readFileSync('domains.txt', 'utf-8')
        .split('\n')
        .filter(l => l.trim() && !l.startsWith('#'))
    : []

  const all = [...new Set([...existing, ...registered])]

  writeFileSync(
    'domains.txt',
    '# Auto-generated by setup-domains.ts\n# Do not edit manually\n\n' + all.join('\n') + '\n'
  )

  p.log.success(`✓ Saved ${registered.length} domain(s) to domains.txt`)
}

if (failed.length > 0) {
  p.log.warn(`⚠️  ${failed.length} domain(s) failed: ${failed.join(', ')}`)
}

if (registered.length === 0) {
  p.outro('No domains registered.')
  process.exit(1)
}

p.outro(`Done — ${registered.length} domain(s) in domains.txt. Run: npm run connect`)
